// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDB4dCQB-yvD90rlhuiidd_rTE7YT-v8-Q',
    appId: '1:1085414527934:android:5c28d533fb6e64423a1fef',
    messagingSenderId: '1085414527934',
    projectId: 'sample-firebase-ai-app-200a6',
    databaseURL: 'https://sample-firebase-ai-app-200a6-default-rtdb.firebaseio.com',
    storageBucket: 'sample-firebase-ai-app-200a6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7PGQ1plswWWh7ok_JP8jR8MbtBeGtrYo',
    appId: '1:1085414527934:ios:57e7af13d7fe74a53a1fef',
    messagingSenderId: '1085414527934',
    projectId: 'sample-firebase-ai-app-200a6',
    databaseURL: 'https://sample-firebase-ai-app-200a6-default-rtdb.firebaseio.com',
    storageBucket: 'sample-firebase-ai-app-200a6.appspot.com',
    iosBundleId: 'com.example.schoolManagementSystem',
  );
}
